### PR TITLE
- ARMEL/ARMEB/ARMHF stuff

### PR DESCRIPTION
**Pull request by BeRo1985**
Hint: It's not final, just the beginning.

### CODE REVIEW

**Comment by LongDirtyAnimAlf** [comment]
Thanks Benjamin work your work !
Did you test your changes ? Have you seen any regression ?

**Comment by BeRo1985** [comment]
But as said, it's still incomplete/not final yet, so you must
complete/finalize it then, if you take my pull reuest as base for the
additional armel/armeb/armhf CPU targets. But the unmodified original "arm" CPU-target should be work as before.

You should therefore regard this pull-request as a starting point for you and not as a finished work.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind testing the new release again ?

And setup+ like included picture.

knipsel

**Comment by BeRo1985** [comment]
A small question, could it be possible that your changes from the newest release are not yet complete on the git repo?

**Comment by BeRo1985** [comment]
It doesn't really work that way after all, see

image

**Comment by LongDirtyAnimAlf** [comment]
Please try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2j
First remove the cross-dir !

**Comment by LongDirtyAnimAlf** [comment]
Marking as solved.
Added arm-arch-options into setup+.

**Pull request closed without merging**
